tests-bullseye:
  stage: test
  image: debian:bullseye
  script:
    - apt-get update
    - apt-get install -y python3 python3-apt python3-yaml python3-coverage python3-pycodestyle pycodestyle python3-pytest python3-pytest-cov git rsync libclass-accessor-perl libdpkg-perl libjson-perl libyaml-syck-perl
    - ci/gitlab-ci-runner --with-coverage
  artifacts:
    when: always
    paths:
     - coverage
     - codestyle

tests-bookworm:
  stage: test
  image: debian:bookworm
  allow_failure: true
  script:
    - apt-get update
    - apt-get install -y python3 python3-apt python3-yaml python3-coverage python3-pycodestyle pycodestyle python3-pytest python3-pytest-cov git rsync libclass-accessor-perl libdpkg-perl libjson-perl libyaml-syck-perl
    - ci/gitlab-ci-runner --with-coverage
  artifacts:
    when: always
    paths:
     - coverage
     - codestyle

docs:
  stage: test
  image: debian:bookworm
  script:
    - apt-get update
    - apt-get install -y python3-sphinx
    - sphinx-build -M html doc _build
    - mv _build/html docs
  artifacts:
    paths:
      - docs
    
pages:
  stage: deploy
  dependencies:
    - docs
    - tests-bullseye
  script:
    - rm -fr public
    - mkdir public
    - mv docs public/docs
    - mv coverage public/coverage
    - mv codestyle public/codestyle
  artifacts:
    paths:
      - public
  only:
    - master
