tests-trixie:
  stage: test
  image: debian:trixie
  allow_failure: true
  script:
    - apt-get update
    - apt-get install -y python3 python3-apt python3-yaml python3-coverage python3-pycodestyle pycodestyle python3-pytest python3-pytest-cov git rsync libclass-accessor-perl libdpkg-perl libjson-perl libyaml-syck-perl
    - ci/gitlab-ci-runner --with-coverage
  artifacts:
    when: always
    paths:
     - coverage
     - codestyle

tests-bookworm:
  stage: test
  image: debian:bookworm
  script:
    - apt-get update
    - apt-get install -y python3 python3-apt python3-yaml python3-coverage python3-pycodestyle pycodestyle python3-pytest python3-pytest-cov git rsync libclass-accessor-perl libdpkg-perl libjson-perl libyaml-syck-perl
    - ci/gitlab-ci-runner --with-coverage
  artifacts:
    when: always
    paths:
     - coverage
     - codestyle

docs:
  stage: test
  image: debian:trixie
  script:
    - apt-get update
    - apt-get install -y python3-sphinx
    - sphinx-build -M html doc _build
    - mv _build/html docs
  artifacts:
    paths:
      - docs
    
pages:
  stage: deploy
  dependencies:
    - docs
    - tests-bookworm
  script:
    - rm -fr public
    - mkdir public
    - mv docs public/docs
    - mv coverage public/coverage
    - mv codestyle public/codestyle
  artifacts:
    paths:
      - public
  only:
    - master

tests-live-2011-12-13:
  stage: test
  image: debian:bookworm
  script:
    - apt-get update
    - apt-get install -y python3 python3-apt python3-yaml git rsync libclass-accessor-perl libdpkg-perl libjson-perl libyaml-syck-perl
    - ci/gitlab-ci-runner --live 2011-12-13
  when: manual
  allow_failure: no
  artifacts:
    when: on_failure
    paths:
     - test-out/

tests-live-2011-12-20:
  stage: test
  image: debian:bookworm
  script:
    - apt-get update
    - apt-get install -y python3 python3-apt python3-yaml git rsync libclass-accessor-perl libdpkg-perl libjson-perl libyaml-syck-perl
    - ci/gitlab-ci-runner --live 2011-12-20
  when: manual
  allow_failure: no
  artifacts:
    when: on_failure
    paths:
     - test-out/

tests-live-2012-01-04-fastest:
  stage: test
  image: debian:bookworm
  script:
    - apt-get update
    - apt-get install -y python3 python3-apt python3-yaml git rsync libclass-accessor-perl libdpkg-perl libjson-perl libyaml-syck-perl
    - ci/gitlab-ci-runner --live 2012-01-04
  when: manual
  allow_failure: no
  artifacts:
    when: on_failure
    paths:
     - test-out/

tests-live-2012-05-09:
  stage: test
  image: debian:bookworm
  script:
    - apt-get update
    - apt-get install -y python3 python3-apt python3-yaml git rsync libclass-accessor-perl libdpkg-perl libjson-perl libyaml-syck-perl
    - ci/gitlab-ci-runner --live 2012-05-09
  when: manual
  artifacts:
    when: on_failure
    paths:
     - test-out/

tests-live-2016-04-11:
  stage: test
  image: debian:bookworm
  script:
    - apt-get update
    - apt-get install -y python3 python3-apt python3-yaml git rsync libclass-accessor-perl libdpkg-perl libjson-perl libyaml-syck-perl
    - ci/gitlab-ci-runner --live 2016-04-11
  when: manual
  artifacts:
    when: on_failure
    paths:
     - test-out/

tests-live-2018-12-18-huge:
  stage: test
  image: debian:bookworm
  script:
    - apt-get update
    - apt-get install -y python3 python3-apt python3-yaml git rsync libclass-accessor-perl libdpkg-perl libjson-perl libyaml-syck-perl
    - ci/gitlab-ci-runner --live 2018-12-18
  when: manual
  artifacts:
    when: on_failure
    paths:
     - test-out/
