#!/bin/sh

set -eu

# Get the force-badtest hints from Debian.

BASEURL=https://release.debian.org/britney/hints
NICKS="adsb elbrus ginggs ivodd jcristau jmw kibi pochu sramacher"
OUTDIR=Hints

if [ ! -d $OUTDIR ]; then
    echo "ERROR: $OUTDIR doesn't exist" >&2
    exit 1
fi

for nick in $NICKS; do
    url=$BASEURL/$nick
    out=$OUTDIR/bad-tests-$nick
    hints=$(wget -nv $url -O- |
        sed '/^ *finished/,$d' |
        grep '^ *force-badtest ' |
        LC_ALL=C sort)

    if [ -z "$hints" ]; then
        rm -f $out
        continue
    fi
    
    {
    echo "# Generated by script: $(basename $0)"
    echo "# From url: $url"
    echo "# On: $(date)"
    echo "$hints"
    } > $out
done
